web:
  build: ./app
  volumes:
    - "./app/polden:/src/polden"
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PORT: 3000
    DB_LINK: db_1
db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"